// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20191101172330_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Land");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("State");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Land = "National",
                            Name = "Carlsbad Caverns",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 2,
                            Land = "National",
                            Name = "Chaco Culture",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 3,
                            Land = "National",
                            Name = "Manhattan Project",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 4,
                            Land = "National",
                            Name = "Pecos",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 5,
                            Land = "National",
                            Name = "Black Canyon Of The Gunnison",
                            State = "CO"
                        },
                        new
                        {
                            ParkId = 6,
                            Land = "National",
                            Name = "Great Sand Dunes",
                            State = "CO"
                        },
                        new
                        {
                            ParkId = 7,
                            Land = "National",
                            Name = "Mesa Verde",
                            State = "CO"
                        },
                        new
                        {
                            ParkId = 8,
                            Land = "National",
                            Name = "Rocky Mountain",
                            State = "CO"
                        },
                        new
                        {
                            ParkId = 9,
                            Land = "State",
                            Name = "Elephant Butte",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 10,
                            Land = "State",
                            Name = "Santa Rosa",
                            State = "NM"
                        },
                        new
                        {
                            ParkId = 11,
                            Land = "State",
                            Name = "Spinney Mountain",
                            State = "CO"
                        },
                        new
                        {
                            ParkId = 12,
                            Land = "State",
                            Name = "Castlewood Canyon",
                            State = "CO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
